# SITE CONFIGURATION
baseurl: ""
url: "https://gouy-antoine.com"

# THEME-SPECIFIC CONFIGURATION
title: Antoine Gouy - Multi.Potentialité.s                                    
# site's title

description: "Libérez vos potentiels. Le site d'un addict aux startups / jeux-vidéo, d'un designer UI/UX, d'un formateur dans la tech/art, d'un ambassadeur Holacracy"      
# used by search engines

avatar: assets/img/content/logo.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: <p>Facilitez les personnes et leur projets par le design et le numérique</p>  # Change Blog header text
header_feature_image: assets/img/content/homebg.jpg
footer_text: >
   Amoureusement développé par votre hôte, herbergé sur GitHub Page et propulsé par <a href="https://jekyllrb.com/">Jekyll</a> avec une belle dose de <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a></br>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                            # Enable if using math markup
google_analytics: UA-44437680-1                        # Tracking ID, e.g. "UA-000000-01"
cookie_consent: true                                   # To respect the usage of cookies
disqus_shortname: https-gouy-antoine-com               # Your discus shortname for comments

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
# remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
